### ISSUE TITLE
Great Work - One hint

### ISSUE THREAD

**Issue by mahop-net** [FluiTec/FluiTec.DatevSharp#1]
Thanks a lot - it saved me a lot of time implementing a Datev Export!

One hint: In your booking HeaderRow there is a field called "Leerfeld"
In my Case, accoring to the sample files of my customer, it is called: "Buchungs GUID"

Kind regards,
Markus

**Comment by IInvocation** [comment]
Thanks for that hint - i'll investigate the documentation to find out if this is normal or customer-specific.

One important tip for you - i'm not using this library in production yet - so the current test's i've done had very little input - which worked fine - but whatever u do - should be verified - feedback on this would be welcome.

**Comment by mahop-net** [comment]
I do not use the complete code. I just copied the field definitions for my export to save the typing work... And I used your .ToDatev() Extentions. I realy like this idea! My tests were good, my customer will test it until the end of the year... If we find problems, I will post them here...
